# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media_choose_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QWidget


class Ui_Dialog(object):
    def setupUi(self, Dialog, media_type='图片'):
        Dialog.setObjectName("Dialog")
        Dialog.resize(446, 295)
        Dialog.setAcceptDrops(False)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 140, 351, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 50, 351, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 210, 351, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("请输入url")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 120, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")


        self.retranslateUi(Dialog, media_type)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, media_type):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请选择" + media_type))
        self.pushButton.setText(_translate("Dialog", "自定义网络" + media_type))
        self.pushButton_2.setText(_translate("Dialog", "选择本地" + media_type))




